// This file was generated by Firebase Genkit.
'use server';
/**
 * @fileOverview This file defines a Genkit flow for extracting order items and quantities from transcribed text.
 *
 * - extractOrderItems - A function that takes transcribed text as input and returns a list of ordered items with quantities.
 * - ExtractOrderItemsInput - The input type for the extractOrderItems function.
 * - ExtractOrderItemsOutput - The return type for the extractOrderItems function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const ExtractOrderItemsInputSchema = z.object({
  transcribedText: z.string().describe('The transcribed text from the conversation between the waiter and the client.'),
});
export type ExtractOrderItemsInput = z.infer<typeof ExtractOrderItemsInputSchema>;

const OrderItemSchema = z.object({
  item: z.string().describe('The name of the item ordered.'),
  quantity: z.number().int().positive().describe('The quantity of the item ordered.'),
});

const ExtractOrderItemsOutputSchema = z.array(OrderItemSchema);
export type ExtractOrderItemsOutput = z.infer<typeof ExtractOrderItemsOutputSchema>;

export async function extractOrderItems(input: ExtractOrderItemsInput): Promise<ExtractOrderItemsOutput> {
  return extractOrderItemsFlow(input);
}

const extractOrderItemsPrompt = ai.definePrompt({
  name: 'extractOrderItemsPrompt',
  input: {
    schema: z.object({
      transcribedText: z.string().describe('The transcribed text from the conversation between the waiter and the client.'),
    }),
  },
  output: {
    schema: z.array(OrderItemSchema).describe('The extracted order items and their quantities.'),
  },
  prompt: `You are an AI assistant that extracts order items and quantities from transcribed text. You will receive the transcribed text from a conversation between a waiter and a client. Your task is to identify the items ordered and their corresponding quantities. Only include items that were requested by the customer.

Transcribed Text: {{{transcribedText}}}

Return the extracted order items and quantities in a JSON array format. Each object in the array should have the following keys: "item" (the name of the item ordered) and "quantity" (the quantity of the item ordered). Do not include any additional information or context in the response, only the JSON array.

For example, if the transcribed text is "Client: I'll have two burgers and a coke. Waiter: Okay, two burgers and a coke.", the output should be: 

[
  {
    "item": "burger",
    "quantity": 2
  },
  {
    "item": "coke",
    "quantity": 1
  }
]
`,
});

const extractOrderItemsFlow = ai.defineFlow<
  typeof ExtractOrderItemsInputSchema,
  typeof ExtractOrderItemsOutputSchema
>({
  name: 'extractOrderItemsFlow',
  inputSchema: ExtractOrderItemsInputSchema,
  outputSchema: ExtractOrderItemsOutputSchema,
},
async input => {
  const {output} = await extractOrderItemsPrompt(input);
  return output!;
});
